### ISSUE TITLE
Can't delete file in window

### ISSUE THREAD

**Issue by ShardanaSoft** [coderaiser/redzip#1]
Hi

I was using cloudcmd and in windows is not working. Looks like this module may be faulty. I'm trying to do a pull request.

fs module return ENOENT instead of ENOTDIR in windows.

**Comment by coderaiser** [comment]
Landed in [v2.2.0](https://github.com/coderaiser/redzip/releases/tag/v2.2.0) 🎉  Is it works for you?

**Comment by ShardanaSoft** [comment]
Yes it works fine!!

Can you tell me the reason why you changed the code? was a bad code? bad for testing? I would like to learn more

**Comment by coderaiser** [comment]
>  Can you tell me the reason why you changed the code? was a bad code? bad for testing? I would like to learn more

Your code was very good, readable and has a lot of sense. The only thing I want to clarify that on `windows` things works differently then on `linux` and `mac os`. And according to [nodejs documentation](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback), is better to do the thing and if it not worked, do another thing because between this calls everything can change. So to be consistent with `node.js` way of doing things and with all other `API` `redzip` provides I changed the code this way.

Thanks a lot for you help!

**Comment by ShardanaSoft** [comment]
that make sense. thanks for spending time to teach me something new.

Happy coding
